[profile.default]
src = "src"
out = "out"
libs = ["lib"]
eth_rpc_url = "https://eth-sepolia.g.alchemy.com/v2/R5qmkW719_cKfUMj_O8reBFoAdPD7xfM"
private_key = "a1593413fd9df872d74a8db5b8139e4822e1105e76db3217d241366a83ae170a"
etherscan_api_key = "XBAC2C716ETDAXBVGNMDGT71NSV44E7IEV"

[profile.networks]
sepolia.chain_id = 11155111


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
